version: "3.9"

services:
  server:
    build: ./server
    working_dir: /code/server
    ports:
      - 3500:3500
    networks:
      - hackathon
    environment:
      - REDIS_URL=redis://redis:6379
      - WEAVIATE_URL=http://weaviate:8080
    volumes:
      - ./server:/code/server
      - shared_data:/code/shared_data
    command: uvicorn app.main:app --host 0.0.0.0 --port 3500 --reload
  redis:
    image: redis:latest
    command: "redis-server"
    ports:
      - 6379:6379
    networks:
      - hackathon
  postgres:
    image: postgres
    command: postgres
    networks:
      - hackathon
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/pgdata
  vdb:
    build: ./vdb
    environment:
      - REDIS_URL=redis://redis:6379
      - WEAVIATE_URL=http://weaviate:8080
    networks:
      - hackathon
    volumes:
      - ./vdb:/code/vdb
      - shared_data:/code/shared_data
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: semitechnologies/weaviate:1.22.2
    ports:
      - 8080:8080
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      CLUSTER_HOSTNAME: "node1"
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
    networks:
      - hackathon
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: 0
    networks:
      - hackathon

volumes:
  shared_data:
  weaviate_data:

networks:
  hackathon:
    name: my-shared-network
