version: "3.9"

services:
  server:
    build: ./server
    working_dir: /code/server
    ports:
      - 3500:3500
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./server:/code/server
      - shared_data:/code/shared_data
    command: uvicorn app.main:app --host 0.0.0.0 --port 3500 --reload
  
  redis:
    image: redis:latest
    command: "redis-server"
    ports:
      - 6379:6379
  
volumes:
  shared_data:
