import { Inter } from "next/font/google";
import "./globals.css";
import Nav from './nav';
import { Suspense } from 'react';
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-gray-50 light">
      <body className={inter.className}>
        <Providers>
          <Suspense>
            <Nav />
          </Suspense>
          {children}
        </Providers>
      </body>
    </html>
  );
}
