import { Inter } from "next/font/google";
import "./globals.css";
import Nav from './nav';
import { Suspense } from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-gray-50">
      <body className={inter.className}>
        <Suspense>
          <Nav />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
